sudo: required
dist: xenial
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: P6+/KRpMuRRCFvq5YIMmQK7xDdqHtI2yPw4rLqlAqrcD6QxykrCCZ9fzrkSqhKbm0xDuZ85A+RWRslCKg3wX3Yy5jpuIma0yUiQiX58zZJQ3mBhHc+KtICPB4RGJBULrBSSXZAKcCpoyJQy8jvJf4b5P0bubMbIqnjajANB/zYPPBjl1ElBQ5TU+rkgMLDIRtp5oYTB/Uwhmy2a31p49Vz5CvMZstZa+nwP5Wb1M11qBd/IAQm+ZNUwm6PuUwFK0VYWIU3Iwrrjz0rwFv/y0k6QO5G9rBoCJO2UDFO+NMwnLKECZj0wpq+B3c1q8RfxayzMoaY3asJ9Oh2ctJWQFMnUykFUro01W/ORPEai9Fn2qPIYk19zvjlR+f39UR9KEyfBUeSvmNtBDLQ5a7d3GqUQtZqWRJTc+xdDeR8A1tST8Y63L700vUDUX7+XE1a8/2HyxmysnJlkKeHNBnURXALq21u1mhjZ47ifYgtNvQRxXYg0qFbnv2nOGhvmd0skLrgW1Plpar78umNPRCifWSYzIkMUWOu1eyPQnl1yl2HQDdQrD4zCKPDsuOa/yQ9KCBpidWW/WZ1K6XiovmAUyC0aTkhYnVOF8yvLsMzAkOx5zcEgo9DpEL1zLLwxaZRVWcslLiBgZZVI9Gtdr5swv2u8IUvQDDJKgRUj84kcG+Qc=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: FdM4Njs11CDr+2Mz2M/ahz9c+RPQpdRYiul0Ko3Hi81oqURdBcyfFwxGcJTvXNbuNsJoYBMhkxu05GjZs6E9+fvqF/K0yT32YmdsA1vAndymNuvBLhG/NfaAcDbzEQCuFjM4zcwHfKzMC1wfbpAGKJvFz355/91/gm1jeX/oKovQ5uYlEOzyd59295lBTicjro6264Qas858rf5E6nC6p1cAWUMqmnq8n2tgpq2tFb0yQI9PzkzTlH0XwP/1eUdVzwXXUOuWl0qklyPWpAlFUvWJFz5SLsg3a2di57mlmM7SPGxzvA3/RtyhxjhVOXhq6rxfOx1TKJ3qg/Yglg8eIRnPTSvOixxiHmZbhi5dWxI0M+Vw+bopm8IlgiWp9hh6JHCiUmVYg19BxCowZeJnSdOfpa3GxdCPNhf3YPEWRZhnOATDVboCIq1l4WpgoRvpFwNeH9fA++xBrZCb5TyAra4yDYxlzBrPpxY942D/UB14AsiKsN+/7+lsH1Mgfu3h1YdLE28tmqT3aNE48HjrZ85LX9o0uflygvnyVa0Q9HNpPVFPSiZodvjtAMc171uBaXlyvoZXwtcs+0qS4QF2rOsL/ILd/9IwdSM6khbyuXRhaT64qT5CYs4ggYWlrFQ5atS7w1OasMEXc9My5FWxPNZrEJkDixxWDGIp45lMv0Q=
